### ISSUE TITLE
Unneeded files

### ISSUE THREAD

**Issue by BartMassey** [CodingInGreen/microbit-v2-project-template#2]
`memory.x` is not needed, I think. `nrf-hal` has one that is dug out of the `target/` directory by `rust-lld`.

I don't know why the `svd/` directory is there.

**Comment by adamhott** [comment]
I removed the svd file and it builds and flashes. But when I remove memory.x I get the following error stemming from build.rs. Do I need a build.rs file in the project?

error: couldn't read memory.x: No such file or directory (os error 2)
  --> build.rs:24:20
   |
24 |         .write_all(include_bytes!("memory.x"))
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by BartMassey** [comment]
Huh. This is strange. You are using the `.cargo/config.toml` that has `rust-lld` and `-Tlink.x`, yes? If you look through your `target/` directory, you should see a `memory.x` deposited by `nrf52833-hal`, I think? `rust-lld` should be able to use `link.x`  from the `cortex-m-rt` crate to find it. Maybe you're not depending on `cortex-m-rt`?

**Comment by adamhott** [comment]
Removed the build.rs file and it compiles and flashes just fine! Updated thanks!
