### ISSUE TITLE
Build and run instructions

### ISSUE THREAD

**Issue by BartMassey** [CodingInGreen/microbit-v2-project-template#3]
Don't need `--target` to build and run: `.cargo/config.toml` takes care of that.

Recommend `cargo embed` instead of `cargo run` by default?

**Comment by BartMassey** [comment]
Should be using `probe-rs run` instead of `probe-run`? I don't remember the history of these tools.

**Comment by adamhott** [comment]
Where should this be modified/added? I'm still learning how to use probe-rs, could you provide a bit more detail? Thanks!

**Comment by BartMassey** [comment]
In `.cargo/config.toml`, you should have a line under `[target.thumbv7em-none-eabihf]` that says `runner = …`, where `…` is `"probe-run --chip nRF52833_xxAA"` or `"probe-rs run --chip nRF52833_xxAA"` . I'm not sure which of these is best to recommend or whether it matters: they both work.

In any case, we may want to recommend in the README that folks run with `cargo embed`, which provides a nicer terminal interface and has a config file that can be used to change behavior. Idk. I use `cargo run` or `cargo embed` depending on what I'm doing: either will work with the config I provided.

**Comment by adamhott** [comment]
Updated with probe-rs run! Thanks!
